version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: node-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI= mongodb://mongo:27017/jamotech

volumes:
  mongo-data:
