FROM node:16.14.0

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your files
COPY . .

# Install nodemon globally (optional, since you're using it in dev)
RUN npm install -g nodemon

# Expose port (assuming Express runs on 3000)
EXPOSE 3000

# Run the dev script
CMD ["npm", "run", "dev"]
